import unittest
from vata_kernel.zk_anchor import VATAZKAnchor

class TestVATAZKLayer(unittest.TestCase):
    def test_map002_witness_generation(self):
        zk_engine = VATAZKAnchor()
        
        # Ingest the exact Merkle Root generated by your LangGraph deep probe
        langgraph_root = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2"
        session_id = "MAP-002-LANGGRAPH-PROBE"
        
        witness = zk_engine.generate_public_witness(langgraph_root, session_id)
        
        print(f"\n[+] ZK Witness successfully compiled for session: {witness['session_id']}")
        print(f"[*] Public Input Elements (Hex Splits): {witness['public_inputs'][:2]}")
        print(f"[*] Target Circuit Status: {witness['status']}")
        
        self.assertEqual(witness["status"], "WITNESS_READY_FOR_CIRCUIT")
        self.assertEqual(len(witness["public_inputs"]), 3)

if __name__ == "__main__":
    unittest.main()
